from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from io import BytesIO
from datetime import datetime


def generate_report_pdf(report: dict) -> BytesIO:
    """Generate a PDF summary of a medical report analysis."""

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle", fontName="Helvetica-Bold", fontSize=18,
        textColor=HexColor("#1e3a8a"), spaceAfter=4
    )
    subtitle_style = ParagraphStyle(
        "SubtitleStyle", fontName="Helvetica", fontSize=10,
        textColor=HexColor("#6b7280"), spaceAfter=16
    )
    section_style = ParagraphStyle(
        "SectionStyle", fontName="Helvetica-Bold", fontSize=13,
        textColor=HexColor("#1e3a8a"), spaceBefore=14, spaceAfter=8
    )
    body_style = ParagraphStyle(
        "BodyStyle", fontName="Helvetica", fontSize=10,
        textColor=HexColor("#1f2937"), spaceAfter=4, leading=14
    )

    story = []

    story.append(Paragraph("MediQuery AI — Report Summary", title_style))
    story.append(Paragraph(
        f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        subtitle_style
    ))

    patient = report.get("patient_info", {})
    story.append(Paragraph("Patient Information", section_style))
    story.append(Paragraph(f"<b>Name:</b> {patient.get('name', 'Unknown')}", body_style))
    story.append(Paragraph(f"<b>Age:</b> {patient.get('age', 'Unknown')}", body_style))
    story.append(Paragraph(f"<b>Gender:</b> {patient.get('gender', 'Unknown')}", body_style))
    story.append(Paragraph(f"<b>Report File:</b> {report.get('filename', 'N/A')}", body_style))

    story.append(Paragraph("Test Results", section_style))

    table_data = [["Test Name", "Value", "Unit", "Normal Range", "Status"]]
    for t in report.get("all_results", []):
        table_data.append([
            t.get("test_name", ""),
            t.get("value", ""),
            t.get("unit", ""),
            t.get("normal_range", ""),
            t.get("status", ""),
        ])

    table = Table(table_data, colWidths=[5.5*cm, 2*cm, 2*cm, 3.5*cm, 2*cm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), HexColor("#1e3a8a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#ffffff")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#d1d5db")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#ffffff"), HexColor("#f3f4f6")]),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(table)

    abnormal = report.get("abnormal_results", [])
    if abnormal:
        story.append(Paragraph("Values Requiring Attention", section_style))
        for a in abnormal:
            story.append(Paragraph(
                f"• <b>{a.get('test_name')}</b>: {a.get('value')} {a.get('unit')} "
                f"— {a.get('status')} ({a.get('severity', 'unknown')} deviation)",
                body_style
            ))
    else:
        story.append(Paragraph("All values are within normal range.", section_style))

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "<i>Disclaimer: This summary is generated by an AI system for informational "
        "purposes only and is not a substitute for professional medical advice. "
        "Please consult a qualified doctor for diagnosis and treatment.</i>",
        ParagraphStyle("Disclaimer", fontName="Helvetica-Oblique", fontSize=8,
                       textColor=HexColor("#9ca3af"), spaceBefore=10)
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer